version: "3.10"

services:
  db:
    image: postgres:14.5
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: ./
    container_name: Api
    command: bash -c "python manage.py runserver 127.0.0.1:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
#    entrypoint: /entrypoint.sh